# configuration for the abdomen-MRCT dataset
# set most parameters to default
# testing `affine_and_freeform` warp type

defaults:
  - default
  - _self_

tag: nlst

dataset:
  name: nlst
  data_root: ./data/NLST
  split: train
  use_mind: True
  aug: False

deploy: True

model:
  # f_maps: [16, 16, 32, 64, 64]
  f_maps: [8]
  name: lkumini
  combine: False    # combine fixed and moving into a single image
  levels: [2, 4]
  output_channels: 12     # number of channels in feature extractor
  init_zero_features: False  # initialize the feature extractor with zeros
  skip: True
  add_image: True

train:
  epochs: 50
  lr: 3e-4
  weight_decay: 0.01
  # train_new_level: [25, 100]    # list should be one less than the number of levels
  train_new_level: [4]    # list should be one less than the number of levels
  backprop_both: False   # do we want to backprop through both the fixed and moving features
  lr_power_decay: 0.9   # polynomial power decay for learning rate
  feature_grad_norm: -1
  image_noise_sigma: 0.0   # how much noise to add to NCC calculation
  cc_smooth_nr: 1e-5       # `smooth_nr` term for numerator
  cc_unsigned: True        # if set to True, will compute the unsigned NCC
  gradient_thresholding: True
  smooth_kps_grad: 0
  kps_threshold: 1.0

loss:
  weight_ncc: 1.0
  weight_kps: 1.0
  weight_jacobian: 0.0
  weight_tv: 0.0
  downsampled_warps: True    # if set to True, will compute the ncc between downsampled moving and fixed images (default)
  downsampled_label_warps: True
  train_last_warp_only: False   # whether to train all layers or just last one
  img_loss: mse

# parameters for diffeomorphic optimization
diffopt: 
  # warp_type: 'affine_and_freeform'
  iterations: [200, 100]
  sigma_warp: 0.5
  sigma_grad: 1.0
  gradual: False
  feature_loss_fn: 'l2'
  phantom_step: adam     
  n_phantom_steps: 1
  convergence_eps: 1e-4
  # warp_type: 'freeform'
  # learning_rate: 3e-4
  warp_type: 'diffeomorphic'
  learning_rate: 0.5

batch_size: 1
num_workers: 4
model_path: Null
save_dir: ''
save_every: 100
